# Generated by Django 3.0.3 on 2020-04-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200403_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='rubruc',
            new_name='rubric',
        ),
    ]
